app = "youtube-livestream-bot"
primary_region = "ord"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[env]
  PORT = "5000"

[[statics]]
  guest_path = "/app/uploads"
  url_prefix = "/uploads/"